import { StylePolygonLayer, StylePolygonExtrusionLayer, StyleLineLayer, StyleBuildingModelLayer, StyleLineExtrusionLayer, StyleLabelLineLayer, StyleOneWayLineLayer, StyleDashedLineLayer, StyleShiftedLineLayer, StylePointLayer, PrivateStyleCircleLayer, StyleLabelingGroupConfig, StyleArrowLayer, StyleRasterLayer, StyleHeatmapLayer, TerrainStyle, StyleMeshLayer, StyleRoadPolygonLayer, StyleGltfModelLayer } from '../types/publicStyles';
export declare function applyDefaultPolygonStyle(userStyle: StylePolygonLayer['style']): Required<StylePolygonLayer['style']>;
export declare function applyDefaultRoadPolygonStyle(userStyle: StyleRoadPolygonLayer['style']): Required<StyleRoadPolygonLayer['style']>;
export declare function applyDefaultMeshStyle(userStyle: StyleMeshLayer['style']): Required<StyleMeshLayer['style']>;
export declare function applyDefaultPolygonExtrusionStyle(userStyle: StylePolygonExtrusionLayer['style']): Required<StylePolygonExtrusionLayer['style']>;
export declare function applyDefaultLineStyle(userStyle: StyleLineLayer['style']): Required<StyleLineLayer['style']>;
export declare function applyDefaultBuildingModelStyle(userStyle: StyleBuildingModelLayer['style']): Required<StyleBuildingModelLayer['style']>;
export declare function applyDefaultLineExtrusionStyle(userStyle: StyleLineExtrusionLayer['style']): Required<StyleLineExtrusionLayer['style']>;
export declare function applyDefaultLabelLineStyle(userStyle: StyleLabelLineLayer['style']): Required<StyleLabelLineLayer['style']>;
export declare function applyDefaultOneWayLineStyle(userStyle: StyleOneWayLineLayer['style']): Required<StyleOneWayLineLayer['style']>;
export declare function applyDefaultDashedLineStyle(userStyle: StyleDashedLineLayer['style']): Required<StyleDashedLineLayer['style']>;
export declare function applyDefaultShiftedLineStyle(userStyle: StyleShiftedLineLayer['style']): Required<StyleShiftedLineLayer['style']>;
export declare function applyDefaultCircleStyle(userStyle: PrivateStyleCircleLayer['style']): Required<PrivateStyleCircleLayer['style']>;
export declare function applyDefaultPointStyle(userStyle: StylePointLayer['style']): Required<StylePointLayer['style']>;
export declare function applyDefaultArrowStyle(userStyle: StyleArrowLayer['style']): Required<StyleArrowLayer['style']>;
export declare function applyDefaultRasterStyle(userStyle: StyleRasterLayer['style']): Required<StyleRasterLayer['style']>;
export declare function applyDefaultHeatmapStyle(userStyle: StyleHeatmapLayer['style']): Required<StyleHeatmapLayer['style']>;
export declare function applyDefaultDemStyle(userStyle: TerrainStyle): Required<TerrainStyle>;
export declare function applyDefaultModelStyle(userStyle: StyleGltfModelLayer['style']): Required<{
    modelSrc?: (string | import("../types/publicStyles").Expression) | undefined;
    offset?: (number | import("../types/publicStyles").Expression) | undefined;
    scale?: (number | import("../types/publicStyles").Expression) | undefined;
    rotation?: (number | import("../types/publicStyles").Expression) | undefined;
    color?: (string | import("../types/publicStyles").Expression) | undefined;
    linkedIds?: (string | import("../types/publicStyles").Expression) | undefined;
    useThreeJs?: boolean | undefined;
    visibility?: ("none" | "visible") | undefined;
}>;
export declare const overlappedGroupName = "__overlapped";
export declare const commercialGroupName = "__commercial";
export declare const defaultGroupName = "default";
export declare const defaultLabelingGroupConfig: Required<StyleLabelingGroupConfig>;
