import { Geometry, Position } from 'geojson';
import { VerticesData } from '../externalTileServer/utils';
export declare const pointGeo: import("geojson").Point;
export declare const pointGeoPoints: Position[];
export declare const transformedPointGeo: VerticesData[];
export declare const multiPointGeo: import("geojson").MultiPoint;
export declare const multiPointGeoPoints: Position[];
export declare const transformedMultiPointGeo: VerticesData[];
export declare const lineStringGeo: import("geojson").LineString;
export declare const lineStringGeoPoints: Position[];
export declare const transformedLineStringGeo: VerticesData[];
export declare const multiLineStringGeo: import("geojson").MultiLineString;
export declare const multiLineStringGeoPoints: any;
export declare const transformedMultiLineStringGeo: VerticesData[];
export declare const polygonGeo: import("geojson").Polygon;
export declare const polygonGeoPoints: Position[];
export declare const transformedPolygonGeo: VerticesData[];
export declare const multiPolygonGeo: import("geojson").MultiPolygon;
export declare const multiPolygonGeoPoints: any;
export declare const transformedMultiPolygonGeo: VerticesData[];
export declare const geometryCollectionGeoPointsQty = 41;
export declare const geometryCollectionGeo: import("geojson").GeometryCollection<Geometry>;
export declare const geometryCollectionGeoPoints: Position[];
export declare const transformedGeometryCollectionGeo: VerticesData[];
