import { MapModules } from '../map/mapModules';
import { GeoPoint, MapState } from '../types';
import { IdentifierResponse } from '../map/identifier';
export declare class Ruler {
    enabled: boolean;
    private joints;
    private needsUpdate;
    private modules;
    private state;
    private polyline?;
    private previewLine?;
    private mouseElem?;
    private snapPoint?;
    private mousePos;
    private popup?;
    private hidePreviewLine;
    private hideMouseElem;
    private draggableJointIndex?;
    private langDiffer;
    constructor(state: MapState, modules: MapModules);
    destroy(): void;
    enable(): void;
    disable(): void;
    update(): void;
    setPoints(points: GeoPoint[]): void;
    handleClick(point: number[], search?: IdentifierResponse): void;
    private onDocumentMouseMove;
    private recalculate;
    private sendRulerChangeEvent;
    private getJointByUniqId;
    private getJointIndexByDistance;
    private getJointIndexByReferer;
    private getPoints;
    private reset;
    private createJoint;
    private addPointToEnd;
    private drawPolyline;
    private requestUpdate;
    private getPreviewPoints;
    private drawPreviewLine;
    private drawMousePoint;
}
