export declare const styles: {
    jointPhase: number;
    jointWidth: number;
    jointBorderWidth: number;
    jointBorder2Width: number;
    jointSmallWidth: number;
    jointSmallBorderWidth: number;
    jointSmallBorder2Width: number;
    jointColor: string;
    jointBorderColor: string;
    jointBorder2Color: string;
    linePhase: number;
    lineWidth: number;
    lineBorderWidth: number;
    lineBorder2Width: number;
    lineColor: string;
    lineBorderColor: string;
    lineBorder2Color: string;
    previewLineColor: string;
    labelFontSize: number;
};
